anyEvent:
  trustOrgMembers: true
  trustCollaborators: true

events:
  push:
    - trustAnyone: true
      paths:
        disallowed: [".github/**", "package.json", "package-lock.json", "README.md"]

  pull_request: &pull_request
      # allow workflow runs, as long as certain paths are not changed.
    - trustAnyone: true
      paths:
        disallowed: [".github/**", "package.json", "package-lock.json"]
        
    - trustedUserNames: ["abstracter-bot"]
      paths:
        allowed: [".github/**"]        
      
      # allow workflow runs with certain paths changes by a specific user name.
    - trustedUserNames: ["eladchen"]
      paths: 
        allowed: ["package.json", "package-lock.json"]

  pull_request_target: *pull_request
