name: Pull Request

on: 
  workflow_dispatch:
    inputs:
      event:
        description: 'Pull-Request Event Payload'
        required: true
        default: '{}'
    
jobs:
  pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Ben"
        uses: eladchen/commit-status@v1
        
      - name: event
        run: echo ${{ toJson(github.event.inputs.event) }} | jq .
        
      - name: event pull request 
        run: |
          echo "${{ fromJson(github.event.inputs.event).pull_request.head.repo.full_name }}"
          echo "${{ fromJson(github.event.inputs.event).pull_request.head.ref }}"
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "${{ fromJson(github.event.inputs.event).pull_request.head.repo.full_name }}"
          ref: "${{ fromJson(github.event.inputs.event).pull_request.head.ref }}"
